### ISSUE TITLE
Config file encryption

### ISSUE THREAD

**Issue by xingweitian** [xingweitian/fund-my-watcard#12]

**Comment by KevinLu** [comment]
I am working on it: 18d6384a57a74e8658a5eb589f847bbe2e528c49

Still need to add encryption to the config fields and decryption when using it.

**Comment by KevinLu** [comment]
Decryption has been added here: 7d19bcdaa9e931edea5ceb78eba62f348dbbf418

The config fields are now encrypted. Feel free to check the code and merge.

**Comment by xingweitian** [comment]
> Decryption has been added here: [7d19bcd](https://github.com/xingweitian/fund-my-watcard/commit/7d19bcdaa9e931edea5ceb78eba62f348dbbf418)
> 
> The config fields are now encrypted. Feel free to check the code and merge.

Thanks!
Please open a PR so that We can merge that to master.

**Comment by KevinLu** [comment]
> 
> 
> > Decryption has been added here: [7d19bcd](https://github.com/xingweitian/fund-my-watcard/commit/7d19bcdaa9e931edea5ceb78eba62f348dbbf418)
> > The config fields are now encrypted. Feel free to check the code and merge.
> 
> Thanks!
> Please open a PR so that We can merge that to master.

We still need to add decryption when using `watcard -f`. Do you want to work on that?

**Comment by xingweitian** [comment]
> > > Decryption has been added here: [7d19bcd](https://github.com/xingweitian/fund-my-watcard/commit/7d19bcdaa9e931edea5ceb78eba62f348dbbf418)
> > > The config fields are now encrypted. Feel free to check the code and merge.
> > 
> > 
> > Thanks!
> > Please open a PR so that We can merge that to master.
> 
> We still need to add decryption when using `watcard -f`. Do you want to work on that?

No problem, I will finish it. You can still open a PR and I will directly make commit to that PR.

**Comment by KevinLu** [comment]
Pull request opened #21 .

**Comment by xingweitian** [comment]
This issue is closed since #21 has been merged.
