### ISSUE TITLE
Attempts to open newly created config with vim

### ISSUE THREAD

**Issue by KevinLu** [xingweitian/fund-my-watcard#20]
The current version of the tool defaults to opening the created config file with vim.

This can result in an error of the config not opening if vim is not installed.

Proposed changes:

- Force user to install vim
- Detect user OS (if Windows: open with notepad)

The code causing the error:
`os.system("vim {}".format(CONFIG_FILE_PATH))`

**Comment by xingweitian** [comment]
Thanks for pointing it out!

Let's improve it in this sprint.

**Comment by xingweitian** [comment]
@KevinLu, I prefer to detect user OS, what do you think?

**Comment by KevinLu** [comment]
Good idea, let's do it.
