### ISSUE TITLE
False positive in validity cheching 

### ISSUE THREAD

**Issue by xingweitian** [xingweitian/fund-my-watcard#58]
https://github.com/xingweitian/fund-my-watcard/blob/master/src/fund_my_watcard/util.py#L130

If I input `San Zhang`, the checker will report an error. White space should be allowed at here.

**Comment by KevinLu** [comment]
How about this regex `/^[a-z ,.'-]+$/i`

**Comment by xingweitian** [comment]
I think `[a-zA-Z\s]+` can be a solution for now. I am working on it and will publish a quick fix version.
