### ISSUE TITLE
Conflict of the installment package

### ISSUE THREAD

**Issue by peterzhangboyun** [xingweitian/fund-my-watcard#9]
When installing the package,  appears the warning as below:
RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version.

**Comment by xingweitian** [comment]
Thanks for figuring it out! In the next sprint, let's find a way to resolve this issue.

**Comment by peterzhangboyun** [comment]
try the command line as below：
sudo pip install --upgrade requests

**Comment by xingweitian** [comment]
Yes, this issue is because that the version of `requests` and `urllib3` are incompatible. Downgrade `urllib3` or upgrade `requests` can fix the warning.
But, I am thinking if there is a better way to resolve this.
